project:
  type: website

website:
  title: "Two Minutes Data Science"
  navbar:
    right:
      - about.qmd
      - icon: youtube
        href: https://www.youtube.com/channel/UCs9ftpNQuO1VSXfNcyUK2qw
      - icon: github
        href: https://github.com/
  search:
    location: navbar
    type: overlay
format:
  html:
    theme: cosmo
    css: styles.css



